title: Blog in the North 
author: Colby Taylor 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is here to do two things. One is to show my progress as I learn to be a web developer.
  Secondly this blog is here to help educate people on the process and maybe help people with a decision 
  to pursue a career change. 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
